---
version: "2.1"
services:
  tf-server:
    build: .
    container_name: tf-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/projects
    volumes:
      - ~/Projects:/projects
    ports:
      - 9001:3000
      - 19001:3001
    restart: unless-stopped